Repository gayanSandamal/choner-mobile, pull requests merged in 2024-11, with the labels that each got.

#60 Challenge Create
  app/(app)/(tabs)/challenges/_layout.tsx
  app/(app)/(tabs)/challenges/index.tsx
  app/(app)/(tabs)/challenges/on-going-challenges.tsx
  app/(app)/(tabs)/community/index.tsx
  components/Base/Button.tsx
  components/Base/Icon.tsx
  components/Base/Icons.tsx
  components/Base/Input.tsx
  components/Common/ChallengePostCard.tsx
  components/Common/Header.tsx
  components/Common/InterestCard.tsx
  components/Common/PostUserItem.tsx
  components/Post/Post.tsx
  components/ProfileOptions/UserProfile.tsx
  constants/values.ts
  types/Components.ts
  utils/commonUtils.ts
Labels: enhancement

#85 Challenge Data format and bug fixes
  app/(app)/(tabs)/challenges/on-going-challenges.tsx
  app/(app)/(tabs)/community/index.tsx
  components/Common/ChallengePostCard.tsx
  types/Components.ts
Labels: bug fix

#92 Feedback page
  app/(app)/(profile)/(settings)/account-settings.tsx
  app/(app)/(profile)/(settings)/settings-home.tsx
  components/Base/Button.tsx
  components/Base/Icon.tsx
  components/Base/Icons.tsx
  components/Common/CircularProgress.tsx
  components/Common/CommentsList.tsx
  components/Common/NavigateBack.tsx
  components/Common/SurveyModal.tsx
  components/Forms/Feedback/index.tsx
  components/PostViews/InterestView.tsx
  components/Widgets/SurveyWidget.tsx
  package-lock.json
  package.json
  types/Components.ts
Labels: enhancement

#94 Challenge create and fetch
  .env
  api/challengePostApi.ts
  api/locationApi.ts
  app/(app)/(profile)/(settings)/settings-home.tsx
  app/(app)/(tabs)/_layout.tsx
  app/(app)/(tabs)/challenges/_layout.tsx
  app/(app)/(tabs)/challenges/index.tsx
  app/(app)/(tabs)/challenges/on-going-challenges.tsx
  app/(app)/(tabs)/community/index.tsx
  app/(app)/_layout.tsx
  app/(app)/product/[id].tsx
  app/(app)/shoppingCart.tsx
  components/Authentications/index.tsx
  components/Base/BottomDrawer.tsx
  components/Base/Icon.tsx
  components/Base/Icons.tsx
  components/Base/Input.tsx
  components/Challenges/OnGoingChallenges.tsx
  components/Common/ChallengePostCard.tsx
  components/Common/CommentsList.tsx
  components/Common/LocationBottomDrawer.tsx
  components/Forms/Feedback/index.tsx
  components/Post/Post.tsx
  constants/values.ts
  hooks/ctx.tsx
  hooks/get/useFetchChallengePosts.ts
  hooks/get/useFetchLocations.tsx
  hooks/mutate/useMutateChallengePosts.ts
  hooks/mutate/useMutateComments.ts
  hooks/useStorageState.ts
  types/Components.ts
  utils/AxiosUtils.ts
  utils/commonUtils.ts
Labels: enhancement

#100 Requested participants
  api/challengePostApi.ts
  app/(app)/(profile)/(settings)/basic-info.tsx
  app/_layout.tsx
  components/Base/Icon.tsx
  components/Base/Icons.tsx
  components/Challenges/RequestedParticipants.tsx
  components/Common/ChallengeViewCard.tsx
  components/Common/CommentsList.tsx
  components/Common/NavigateBack.tsx
  components/PostViews/ChallengeView.tsx
  components/ProfileOptions/UpdateBasicInfo.tsx
  constants/values.ts
  hooks/get/useFetchChallengePosts.ts
  hooks/mutate/useMutateChallengePosts.ts
  package-lock.json
  package.json
  types/Components.ts
  utils/commonUtils.ts
Labels: enhancement

#101 Location in interests/ Participants view in Challenges
  api/challengePostApi.ts
  api/interestPostApi.ts
  app/(app)/(tabs)/interests/index.tsx
  components/Challenges/JoinedParticipants.tsx
  components/Challenges/RequestedParticipants.tsx
  components/Common/ChallengeViewCard.tsx
  components/Common/InterestCard.tsx
  components/Post/Post.tsx
  components/PostViews/ChallengeView.tsx
  components/PostViews/InterestView.tsx
  constants/values.ts
  hooks/get/useFetchChallengePosts.ts
  hooks/mutate/useMutateChallengePosts.ts
  types/Components.ts
  utils/commonUtils.ts
Labels: enhancement

#102 Dashboard items
  api/interestPostApi.ts
  app/(app)/(tabs)/index.tsx
  components/AutoSliders/CommunityPostsAutoSlider.tsx
  components/AutoSliders/InterestsAutoSlider.tsx
  components/Base/Icon.tsx
  components/Base/Icons.tsx
  components/Challenges/JoinedParticipants.tsx
  components/Common/CommunityPostCard.tsx
  components/Common/InterestCard.tsx
  components/PostViews/ChallengeView.tsx
  components/PostViews/CommunityView.tsx
  components/PostViews/InterestView.tsx
  components/ProfileOptions/UserProfile.tsx
  components/Widgets/DiagnosisWidget.tsx
  components/Widgets/InterestsWidget.tsx
  constants/NavigationTabs.ts
  constants/values.ts
  hooks/get/useFetchInterestPosts.ts
  package-lock.json
  package.json
  types/Components.ts
  utils/commonUtils.ts
Labels: enhancement

#103 Survey
  api/surveyApi.ts
  app/(app)/(tabs)/index.tsx
  app/(app)/_layout.tsx
  app/(app)/survey.tsx
  components/Authentications/SignIn.tsx
  components/Authentications/SignUp.tsx
  components/Authentications/index.tsx
  components/Common/SurveyModal.tsx
  components/ProfileOptions/UserProfile.tsx
  components/Widgets/SurveyWidget.tsx
  constants/values.ts
  hooks/ctx.tsx
  hooks/get/useFetchSurvey.ts
  hooks/mutate/useMutateSurvey.ts
  types/Components.ts
Labels: enhancement

#106 Expo SDK upgrade from 51 to 52
  app.json
  app/(app)/(tabs)/_layout.tsx
  app/(app)/(tabs)/challenges/index.tsx
  app/(app)/(tabs)/index.tsx
  app/(app)/(tabs)/interests/index.tsx
  auth.js
  components/Authentications/SignUp.tsx
  components/Base/Icons.tsx
  components/Common/SurveyModal.tsx
  components/Post/Post.tsx
  constants/NavigationTabs.ts
  package-lock.json
  package.json
  types/Components.ts
Labels: bug

#108 bug fixes
  .env
  .gitignore
  app.json
  app/(app)/(profile)/(settings)/account-settings.tsx
  app/(app)/(profile)/(settings)/settings-home.tsx
  app/(app)/(tabs)/_layout.tsx
  app/(app)/(tabs)/challenges/challenge-view.tsx
  app/(app)/(tabs)/challenges/index.tsx
  app/(app)/(tabs)/community/community-view.tsx
  app/(app)/(tabs)/community/index.tsx
  app/(app)/(tabs)/interests/index.tsx
  app/(app)/(tabs)/interests/interest-view.tsx
  app/(app)/survey.tsx
  assets/styles/common.ts
  components/Authentications/ForgotPassword.tsx
  components/Authentications/SignIn.tsx
  components/Authentications/SignUp.tsx
  components/Authentications/index.tsx
  components/Base/Icons.tsx
  components/Base/Input.tsx
  components/Challenges/JoinedParticipants.tsx
  components/Challenges/OnGoingChallenges.tsx
  components/Challenges/RequestedParticipants.tsx
  components/Common/InterestCard.tsx
  components/Common/LocationBottomDrawer.tsx
  components/Common/SurveyModal.tsx
  components/Post/Post.tsx
  components/PostViews/ChallengeView.tsx
  components/PostViews/CommunityView.tsx
  components/PostViews/InterestView.tsx
  components/ProfileOptions/UpdateBasicInfo.tsx
  components/ProfileOptions/UserProfile.tsx
  constants/Colors.ts
  package-lock.json
  tailwind.config.js
Labels: bug fix

#109 App icons and loading icon
  app.json
  app/(app)/(tabs)/_layout.tsx
  app/(app)/_layout.tsx
  assets/images/icon.png
  assets/images/splash.png
  assets/styles/common.ts
Labels: enhancement
